# Generated by Django 2.2.16 on 2020-10-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agents',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userprofile_agents_+', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('manager', 'Manager')], default=None, max_length=15, null=True),
        ),
    ]
