# Generated by Django 2.2.16 on 2020-10-01 15:44

from django.db import migrations, models
import invoice.validators


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[invoice.validators.validate_file_attachment]),
        ),
    ]
